### ISSUE TITLE
The specified superclass 'matlab.system.mixin.internal.SampleTime' contains a parse error

### ISSUE THREAD

**Issue by AeroBIade** [Kinovarobotics/matlab_Kinovaapi_wrapper#10]
Hi,

I compile the mex file in Matlab2020b and try to connect to a Mico arm. But I got this error message. Does anyone know how to fix it?

`Error using JacoComm
The specified superclass 'matlab.system.mixin.internal.SampleTime' contains a parse error, cannot be found
on MATLAB's search path, or is shadowed by another file with the same name.

Error in testJacoComm (line 16)
jc = JacoComm`

Thanks!

**Comment by PyLuke73** [comment]
Hello @AeroBIade ,
I had the same problem.
I removed the "internal" and now it works.
Let me know
Good Luck
Luca

**Comment by akshay22k** [comment]
Hi @PyLuke73 

I am having the same problem. Where did you remove the "internal" from? Please let me know. Thanks!

Best wishes, 

Akshay

**Comment by anubhav-dogra** [comment]
In JacoComm.m file,
classdef JacoComm < matlab.System & matlab.system.mixin.Propagates ...
        & matlab.system.mixin.CustomIcon ...
        & **matlab.system.mixin.**internal**.SampleTime
