### ISSUE TITLE
Matlab 2015b and jaco arm 

### ISSUE THREAD

**Issue by AsmaRoshaan** [Kinovarobotics/matlab_Kinovaapi_wrapper#2]
Hi I want to operate jaco robotic arm from windows 7 32bit/windows 10 and matlab 2015a or b . But the problem is matlab isn't supporting any compiler to run c++ code line. I have installed and tried almost everything. Can some one help me in this regard?

**Comment by samuelhovington** [comment]
Hi AsmaRoshaan,

Can you explain a little more what is exactly the issue? What did you try? Because Matlab is actually supporting many compilers for C++.

**Comment by AsmaRoshaan** [comment]
I am using gtec gUSbamp on windows 7 32bit with matlab API. My matlab code is running perfectly fine but now I want the output of my code as an input to send commands to jaco robotic arm. Now the matlab code of robotic arm works with windows 10 Matlab 2017. But I want to run it with matlab 2015a or 2015b on windows 7 32bit. Now Both matlab 2015 a or b are not supporting the compilers i.e microsoft visual 2015 or windows SDK 7.1. It only shows lccwin32 as compiler. I tried matlab 2015 a or b with windows 10 but the code is still not working.

**Comment by samuelhovington** [comment]
I think it's because you are on a 32bit version of Windows. I suggest you to try two things :
Try running your code on a 64bit version of windows.
Try to run the matlab_Kinovaapi_wrapper standalone, if you are not able, it's probably because of your architecture.
