### ISSUE TITLE
KINOVA PI #$%^ OR Jaco Robotical Arm ????

### ISSUE THREAD

**Issue by AsmaRoshaan** [Kinovarobotics/matlab_Kinovaapi_wrapper#3]
Hi 
I am having an issue related to the jaco arm drivers. I installed jaco arm 2 on windows 10. It came with the device name "kinova pi (chinese words)" and drivers installation had no issue. Commands worked perfectly fine using matlab 2017b.
I installed that same jaco arm 2 on the second port. It installed with a name " Jacp robotical arm" using jacosoft drivers. Drivers got installed but matlab code is not working.Robot got connected but nothing is happening. Its not taking any values from robot neither send any command to robot. 
WHY IS THAT ? It works only when " kinova pi" driver is installed on all the ports. 
The problem is I want to use the same robot on windows 8 and it doesnot take any other driver except jacosot service drivers and device name comes as " jaco robotical arm" and it gets connect but its usefull. because it doesn't execute any command without giving any error. Can you tell me what is the problem????

**Comment by nsaif-kinova** [comment]
Hello AsmaRoshaan,
Please contact support@kinova.ca they will be able to help you install the drivers properly.
Sincerely,
