### ISSUE TITLE
Run Kinova jaco from matlab using Ethernet connection

### ISSUE THREAD

**Issue by AsmaRoshaan** [Kinovarobotics/matlab_Kinovaapi_wrapper#4]
Hi 
I am trying to operate the jaco arm from matlab using ethernet settings. Ethernet settings are fine. I can use the arm from development center gui but I can not use it from matlab? Any idea why ? What changes should I make in the code? I have changed the commandlayerwindows.dll to commandlayerethernet.dll in jacosdkwrapper and then generated a new mex file but the error is still the same. 
The error is : No device found. Libraries and initializing api is successful.

**Comment by samuelhovington** [comment]
Hi AsmaRoshann,
The matlab_Kinovaapi_wrapper does not officially support the Ethernet connection. The functions are mostly the same for both USB and Ethernet connection but, you will need to make some modifications to make it works.
The first modification you made seems good, but I think you also have to change the InitAPI function for InitEternetAPI in JacoSDKWrapper.cpp.

Sincerely,

**Comment by samuelhovington** [comment]
Hi AsmaRoshaan,
I made the modifications on my side and I committed the changes to the master branch. You just have to merge it with your code, select the right dll in JacoSDKWrapper.cpp and generate a new mex file. Then you should be able to connect the arm with Ethernet.

Sincerely,

**Comment by AsmaRoshaan** [comment]
I tried it and It's Working. Thank YOU :)
